@echo off
echo Starting Budget Buddy (Full Stack) on Windows...

echo Starting Backend Server...
start cmd /k "npm run dev"

echo Starting Frontend...
cd frontend
start cmd /k "npm run start:windows"

echo Budget Buddy is starting up! Please wait a moment...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000 